{{- $dep := .Values.dependencies.loki -}}
{{- $shouldInstall := include "rhoai-dependencies.shouldInstall" (dict
  "dependencyName" "loki"
  "dependency" $dep
  "root" $
) -}}
{{- if eq $shouldInstall "true" }}
{{- if eq (include "rhoai-dependencies.isOlmMode" $) "true" }}
{{ include "rhoai-dependencies.operator.olm" (dict
  "name" $dep.olm.name
  "namespace" $dep.olm.namespace
  "channel" $dep.olm.channel
  "createNamespace" $dep.olm.createNamespace
  "version" $dep.olm.version
  "config" $dep.olm.config
  "root" $
) }}
{{- end }}
{{- end }}
